Name:           ros-melodic-moveit-sim-controller
Version:        0.2.0
Release:        1%{?dist}
Summary:        ROS moveit_sim_controller package

Group:          Development/Libraries
License:        BSD
URL:            https://github.com/davetcoleman/moveit_sim_controller
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-moveit-core
Requires:       ros-melodic-moveit-ros-planning
Requires:       ros-melodic-ros-control-boilerplate
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-rosparam-shortcuts
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-moveit-core
BuildRequires:  ros-melodic-moveit-ros-planning
BuildRequires:  ros-melodic-ros-control-boilerplate
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-roslint
BuildRequires:  ros-melodic-rosparam-shortcuts

%description
A simulation interface for a hardware interface for ros_control, and loads
default joint values from SRDF

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Wed Sep 18 2019 Dave Coleman <davetcoleman@gmail.com> - 0.2.0-1
- Autogenerated by Bloom

* Fri Jun 01 2018 Dave Coleman <davetcoleman@gmail.com> - 0.1.0-0
- Autogenerated by Bloom

